# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install .NET 8
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0

    - name: Install .NET MAUI Workload
      run: dotnet workload install maui
      # if: runner.os == 'macOS' # reenable when .NET 8 is default on hosted runners

    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
      if: runner.os == 'macOS' # Remove when Xcode 15+ is default on the hosted runners

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-${{ github.event.repository.updated_at}}
        path: TestResults-${{ github.event.repository.updated_at}}
        if: ${{ always() }}
